
server:
  port: 8080
  

spring:

# BANCO MYSQL
  jpa:
    database: mysql
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    
  
  datasource:
    url: jdbc:mysql://localhost:3306/sentinela?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root


  flyway:
    enabled: true
    locations: classpath:db/migration/mysql